-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table event_log (
  id                            bigint generated by default as identity not null,
  timestamp                     timestamptz,
  event_type                    varchar(255),
  constraint pk_event_log primary key (id)
);


-- !Downs

-- drop all
drop table if exists event_log cascade;

